// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.8
// source: internal/infrastructure/rpc/proto/clink/clink.proto

package clink

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Kind int32

const (
	Kind_VESTIGE   Kind = 0
	Kind_APPRAISAL Kind = 1
	Kind_USER      Kind = 2
)

// Enum value maps for Kind.
var (
	Kind_name = map[int32]string{
		0: "VESTIGE",
		1: "APPRAISAL",
		2: "USER",
	}
	Kind_value = map[string]int32{
		"VESTIGE":   0,
		"APPRAISAL": 1,
		"USER":      2,
	}
)

func (x Kind) Enum() *Kind {
	p := new(Kind)
	*p = x
	return p
}

func (x Kind) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Kind) Descriptor() protoreflect.EnumDescriptor {
	return file_internal_infrastructure_rpc_proto_clink_clink_proto_enumTypes[0].Descriptor()
}

func (Kind) Type() protoreflect.EnumType {
	return &file_internal_infrastructure_rpc_proto_clink_clink_proto_enumTypes[0]
}

func (x Kind) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Kind.Descriptor instead.
func (Kind) EnumDescriptor() ([]byte, []int) {
	return file_internal_infrastructure_rpc_proto_clink_clink_proto_rawDescGZIP(), []int{0}
}

type VestigeCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Parent  string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	Head    string `protobuf:"bytes,2,opt,name=head,proto3" json:"head,omitempty"`
	Title   string `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Content string `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Hit     int64  `protobuf:"varint,5,opt,name=hit,proto3" json:"hit,omitempty"`
	UserId  string `protobuf:"bytes,6,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Address string `protobuf:"bytes,7,opt,name=address,proto3" json:"address,omitempty"`
	Error   string `protobuf:"bytes,8,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *VestigeCreateRequest) Reset() {
	*x = VestigeCreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_infrastructure_rpc_proto_clink_clink_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VestigeCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VestigeCreateRequest) ProtoMessage() {}

func (x *VestigeCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infrastructure_rpc_proto_clink_clink_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VestigeCreateRequest.ProtoReflect.Descriptor instead.
func (*VestigeCreateRequest) Descriptor() ([]byte, []int) {
	return file_internal_infrastructure_rpc_proto_clink_clink_proto_rawDescGZIP(), []int{0}
}

func (x *VestigeCreateRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *VestigeCreateRequest) GetHead() string {
	if x != nil {
		return x.Head
	}
	return ""
}

func (x *VestigeCreateRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *VestigeCreateRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *VestigeCreateRequest) GetHit() int64 {
	if x != nil {
		return x.Hit
	}
	return 0
}

func (x *VestigeCreateRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *VestigeCreateRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *VestigeCreateRequest) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type AppraisalCreateRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value     int64  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	VestigeId string `protobuf:"bytes,2,opt,name=vestige_id,json=vestigeId,proto3" json:"vestige_id,omitempty"`
	NextId    string `protobuf:"bytes,3,opt,name=next_id,json=nextId,proto3" json:"next_id,omitempty"`
	UserId    string `protobuf:"bytes,4,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Address   string `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	Error     string `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *AppraisalCreateRequest) Reset() {
	*x = AppraisalCreateRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_infrastructure_rpc_proto_clink_clink_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AppraisalCreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppraisalCreateRequest) ProtoMessage() {}

func (x *AppraisalCreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infrastructure_rpc_proto_clink_clink_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppraisalCreateRequest.ProtoReflect.Descriptor instead.
func (*AppraisalCreateRequest) Descriptor() ([]byte, []int) {
	return file_internal_infrastructure_rpc_proto_clink_clink_proto_rawDescGZIP(), []int{1}
}

func (x *AppraisalCreateRequest) GetValue() int64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *AppraisalCreateRequest) GetVestigeId() string {
	if x != nil {
		return x.VestigeId
	}
	return ""
}

func (x *AppraisalCreateRequest) GetNextId() string {
	if x != nil {
		return x.NextId
	}
	return ""
}

func (x *AppraisalCreateRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AppraisalCreateRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *AppraisalCreateRequest) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type TxHashResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind   Kind   `protobuf:"varint,1,opt,name=kind,proto3,enum=clink.Kind" json:"kind,omitempty"`
	TxHash string `protobuf:"bytes,2,opt,name=tx_hash,json=txHash,proto3" json:"tx_hash,omitempty"`
	Error  string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *TxHashResponse) Reset() {
	*x = TxHashResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_infrastructure_rpc_proto_clink_clink_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TxHashResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TxHashResponse) ProtoMessage() {}

func (x *TxHashResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infrastructure_rpc_proto_clink_clink_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TxHashResponse.ProtoReflect.Descriptor instead.
func (*TxHashResponse) Descriptor() ([]byte, []int) {
	return file_internal_infrastructure_rpc_proto_clink_clink_proto_rawDescGZIP(), []int{2}
}

func (x *TxHashResponse) GetKind() Kind {
	if x != nil {
		return x.Kind
	}
	return Kind_VESTIGE
}

func (x *TxHashResponse) GetTxHash() string {
	if x != nil {
		return x.TxHash
	}
	return ""
}

func (x *TxHashResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ConfirmRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind  Kind   `protobuf:"varint,1,opt,name=kind,proto3,enum=clink.Kind" json:"kind,omitempty"`
	Id    string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"` // txHash or userId or else
	Error string `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *ConfirmRequest) Reset() {
	*x = ConfirmRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_infrastructure_rpc_proto_clink_clink_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfirmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmRequest) ProtoMessage() {}

func (x *ConfirmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infrastructure_rpc_proto_clink_clink_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmRequest.ProtoReflect.Descriptor instead.
func (*ConfirmRequest) Descriptor() ([]byte, []int) {
	return file_internal_infrastructure_rpc_proto_clink_clink_proto_rawDescGZIP(), []int{3}
}

func (x *ConfirmRequest) GetKind() Kind {
	if x != nil {
		return x.Kind
	}
	return Kind_VESTIGE
}

func (x *ConfirmRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ConfirmRequest) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type ConfirmResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Kind      Kind   `protobuf:"varint,1,opt,name=kind,proto3,enum=clink.Kind" json:"kind,omitempty"`
	Id        string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"` // txHash or userId or else
	Confirmed bool   `protobuf:"varint,3,opt,name=confirmed,proto3" json:"confirmed,omitempty"`
	Error     string `protobuf:"bytes,4,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *ConfirmResponse) Reset() {
	*x = ConfirmResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_infrastructure_rpc_proto_clink_clink_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConfirmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmResponse) ProtoMessage() {}

func (x *ConfirmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_internal_infrastructure_rpc_proto_clink_clink_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmResponse.ProtoReflect.Descriptor instead.
func (*ConfirmResponse) Descriptor() ([]byte, []int) {
	return file_internal_infrastructure_rpc_proto_clink_clink_proto_rawDescGZIP(), []int{4}
}

func (x *ConfirmResponse) GetKind() Kind {
	if x != nil {
		return x.Kind
	}
	return Kind_VESTIGE
}

func (x *ConfirmResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ConfirmResponse) GetConfirmed() bool {
	if x != nil {
		return x.Confirmed
	}
	return false
}

func (x *ConfirmResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_internal_infrastructure_rpc_proto_clink_clink_proto protoreflect.FileDescriptor

var file_internal_infrastructure_rpc_proto_clink_clink_proto_rawDesc = []byte{
	0x0a, 0x33, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x69, 0x6e, 0x66, 0x72, 0x61,
	0x73, 0x74, 0x72, 0x75, 0x63, 0x74, 0x75, 0x72, 0x65, 0x2f, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x2f, 0x63, 0x6c, 0x69, 0x6e, 0x6b, 0x2f, 0x63, 0x6c, 0x69, 0x6e, 0x6b, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x63, 0x6c, 0x69, 0x6e, 0x6b, 0x22, 0xcd, 0x01, 0x0a,
	0x14, 0x56, 0x65, 0x73, 0x74, 0x69, 0x67, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x61, 0x72, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x68, 0x65, 0x61, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x68, 0x65, 0x61,
	0x64, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e,
	0x74, 0x12, 0x10, 0x0a, 0x03, 0x68, 0x69, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03,
	0x68, 0x69, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18,
	0x08, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0xaf, 0x01, 0x0a,
	0x16, 0x41, 0x70, 0x70, 0x72, 0x61, 0x69, 0x73, 0x61, 0x6c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1d, 0x0a,
	0x0a, 0x76, 0x65, 0x73, 0x74, 0x69, 0x67, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x76, 0x65, 0x73, 0x74, 0x69, 0x67, 0x65, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07,
	0x6e, 0x65, 0x78, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e,
	0x65, 0x78, 0x74, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x18,
	0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x60,
	0x0a, 0x0e, 0x54, 0x78, 0x48, 0x61, 0x73, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1f, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0b,
	0x2e, 0x63, 0x6c, 0x69, 0x6e, 0x6b, 0x2e, 0x4b, 0x69, 0x6e, 0x64, 0x52, 0x04, 0x6b, 0x69, 0x6e,
	0x64, 0x12, 0x17, 0x0a, 0x07, 0x74, 0x78, 0x5f, 0x68, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x74, 0x78, 0x48, 0x61, 0x73, 0x68, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x22, 0x57, 0x0a, 0x0e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1f, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e,
	0x32, 0x0b, 0x2e, 0x63, 0x6c, 0x69, 0x6e, 0x6b, 0x2e, 0x4b, 0x69, 0x6e, 0x64, 0x52, 0x04, 0x6b,
	0x69, 0x6e, 0x64, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x76, 0x0a, 0x0f, 0x43, 0x6f, 0x6e,
	0x66, 0x69, 0x72, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x04,
	0x6b, 0x69, 0x6e, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0b, 0x2e, 0x63, 0x6c, 0x69,
	0x6e, 0x6b, 0x2e, 0x4b, 0x69, 0x6e, 0x64, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x1c, 0x0a,
	0x09, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08,
	0x52, 0x09, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x65, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x2a, 0x2c, 0x0a, 0x04, 0x4b, 0x69, 0x6e, 0x64, 0x12, 0x0b, 0x0a, 0x07, 0x56, 0x45, 0x53,
	0x54, 0x49, 0x47, 0x45, 0x10, 0x00, 0x12, 0x0d, 0x0a, 0x09, 0x41, 0x50, 0x50, 0x52, 0x41, 0x49,
	0x53, 0x41, 0x4c, 0x10, 0x01, 0x12, 0x08, 0x0a, 0x04, 0x55, 0x53, 0x45, 0x52, 0x10, 0x02, 0x32,
	0xcf, 0x01, 0x0a, 0x05, 0x43, 0x6c, 0x69, 0x6e, 0x6b, 0x12, 0x43, 0x0a, 0x0d, 0x56, 0x65, 0x73,
	0x74, 0x69, 0x67, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x12, 0x1b, 0x2e, 0x63, 0x6c, 0x69,
	0x6e, 0x6b, 0x2e, 0x56, 0x65, 0x73, 0x74, 0x69, 0x67, 0x65, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x63, 0x6c, 0x69, 0x6e, 0x6b, 0x2e,
	0x54, 0x78, 0x48, 0x61, 0x73, 0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x47,
	0x0a, 0x0f, 0x41, 0x70, 0x70, 0x72, 0x61, 0x69, 0x73, 0x61, 0x6c, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x12, 0x1d, 0x2e, 0x63, 0x6c, 0x69, 0x6e, 0x6b, 0x2e, 0x41, 0x70, 0x70, 0x72, 0x61, 0x69,
	0x73, 0x61, 0x6c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x15, 0x2e, 0x63, 0x6c, 0x69, 0x6e, 0x6b, 0x2e, 0x54, 0x78, 0x48, 0x61, 0x73, 0x68, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x38, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x72, 0x6d, 0x12, 0x15, 0x2e, 0x63, 0x6c, 0x69, 0x6e, 0x6b, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x72, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x16, 0x2e, 0x63, 0x6c, 0x69, 0x6e,
	0x6b, 0x2e, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x72, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x42, 0x21, 0x5a, 0x1f, 0x6c, 0x61, 0x79, 0x65, 0x72, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72,
	0x6e, 0x61, 0x6c, 0x2f, 0x70, 0x6f, 0x72, 0x74, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2f, 0x63,
	0x6c, 0x69, 0x6e, 0x6b, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_infrastructure_rpc_proto_clink_clink_proto_rawDescOnce sync.Once
	file_internal_infrastructure_rpc_proto_clink_clink_proto_rawDescData = file_internal_infrastructure_rpc_proto_clink_clink_proto_rawDesc
)

func file_internal_infrastructure_rpc_proto_clink_clink_proto_rawDescGZIP() []byte {
	file_internal_infrastructure_rpc_proto_clink_clink_proto_rawDescOnce.Do(func() {
		file_internal_infrastructure_rpc_proto_clink_clink_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_infrastructure_rpc_proto_clink_clink_proto_rawDescData)
	})
	return file_internal_infrastructure_rpc_proto_clink_clink_proto_rawDescData
}

var file_internal_infrastructure_rpc_proto_clink_clink_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_internal_infrastructure_rpc_proto_clink_clink_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_internal_infrastructure_rpc_proto_clink_clink_proto_goTypes = []interface{}{
	(Kind)(0),                      // 0: clink.Kind
	(*VestigeCreateRequest)(nil),   // 1: clink.VestigeCreateRequest
	(*AppraisalCreateRequest)(nil), // 2: clink.AppraisalCreateRequest
	(*TxHashResponse)(nil),         // 3: clink.TxHashResponse
	(*ConfirmRequest)(nil),         // 4: clink.ConfirmRequest
	(*ConfirmResponse)(nil),        // 5: clink.ConfirmResponse
}
var file_internal_infrastructure_rpc_proto_clink_clink_proto_depIdxs = []int32{
	0, // 0: clink.TxHashResponse.kind:type_name -> clink.Kind
	0, // 1: clink.ConfirmRequest.kind:type_name -> clink.Kind
	0, // 2: clink.ConfirmResponse.kind:type_name -> clink.Kind
	1, // 3: clink.Clink.VestigeCreate:input_type -> clink.VestigeCreateRequest
	2, // 4: clink.Clink.AppraisalCreate:input_type -> clink.AppraisalCreateRequest
	4, // 5: clink.Clink.Confirm:input_type -> clink.ConfirmRequest
	3, // 6: clink.Clink.VestigeCreate:output_type -> clink.TxHashResponse
	3, // 7: clink.Clink.AppraisalCreate:output_type -> clink.TxHashResponse
	5, // 8: clink.Clink.Confirm:output_type -> clink.ConfirmResponse
	6, // [6:9] is the sub-list for method output_type
	3, // [3:6] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_internal_infrastructure_rpc_proto_clink_clink_proto_init() }
func file_internal_infrastructure_rpc_proto_clink_clink_proto_init() {
	if File_internal_infrastructure_rpc_proto_clink_clink_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_infrastructure_rpc_proto_clink_clink_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VestigeCreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_infrastructure_rpc_proto_clink_clink_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AppraisalCreateRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_infrastructure_rpc_proto_clink_clink_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TxHashResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_infrastructure_rpc_proto_clink_clink_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfirmRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_infrastructure_rpc_proto_clink_clink_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConfirmResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_infrastructure_rpc_proto_clink_clink_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_infrastructure_rpc_proto_clink_clink_proto_goTypes,
		DependencyIndexes: file_internal_infrastructure_rpc_proto_clink_clink_proto_depIdxs,
		EnumInfos:         file_internal_infrastructure_rpc_proto_clink_clink_proto_enumTypes,
		MessageInfos:      file_internal_infrastructure_rpc_proto_clink_clink_proto_msgTypes,
	}.Build()
	File_internal_infrastructure_rpc_proto_clink_clink_proto = out.File
	file_internal_infrastructure_rpc_proto_clink_clink_proto_rawDesc = nil
	file_internal_infrastructure_rpc_proto_clink_clink_proto_goTypes = nil
	file_internal_infrastructure_rpc_proto_clink_clink_proto_depIdxs = nil
}
